using System;

namespace Oluso.SourceGenerators;

/// <summary>
/// Simple constants values
/// </summary>
public class Constants
{
    /// <summary>
    /// Current version
    /// </summary>
    public static string Version = "0.3.14";
    
    /// <summary>
    /// Header to place in all generated source code 
    /// </summary>
    public static string CodeHeader = $@"// ------------------------------------------------------------------------------
// <autogenerated>
//      This code has been generated using Oluso  v{Version} tool.
//
//      Changes to this ile may cause incorrect behavior and will be lost if
//      the code is regenerated. 
// </autogenerated>
// ------------------------------------------------------------------------------"
        .Replace("\r\n", "\n");
}