//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oluso.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oluso.Email.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {directoryPath} not found.
        /// </summary>
        internal static string MsgDirectoryNotFound {
            get {
                return ResourceManager.GetString("MsgDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address could not be null, empty or whitespace.
        /// </summary>
        internal static string MsgEmailAddressCouldNotBeNull {
            get {
                return ResourceManager.GetString("MsgEmailAddressCouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address {email} is invalid.
        /// </summary>
        internal static string MsgEmailAddressIsInvalid {
            get {
                return ResourceManager.GetString("MsgEmailAddressIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email attachment could not be null.
        /// </summary>
        internal static string MsgEmailAttachmentCouldNotBeNull {
            get {
                return ResourceManager.GetString("MsgEmailAttachmentCouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email attachment {filePath} not found.
        /// </summary>
        internal static string MsgEmailAttachmentNotFound {
            get {
                return ResourceManager.GetString("MsgEmailAttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email body could not be null, empty or whitespace.
        /// </summary>
        internal static string MsgEmailBodyCoudNotBeNull {
            get {
                return ResourceManager.GetString("MsgEmailBodyCoudNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email could not be sent.
        /// </summary>
        internal static string MsgEmailCouldNotBeSend {
            get {
                return ResourceManager.GetString("MsgEmailCouldNotBeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email from address could not be null.
        /// </summary>
        internal static string MsgEmailFromCouldNotBeNull {
            get {
                return ResourceManager.GetString("MsgEmailFromCouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email, please wait...
        /// </summary>
        internal static string MsgEmailSendingPleaseWait {
            get {
                return ResourceManager.GetString("MsgEmailSendingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        internal static string MsgEmailSentSuccessfully {
            get {
                return ResourceManager.GetString("MsgEmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template directory {templateDir} not found.
        /// </summary>
        internal static string MsgEmailTemplateDirectoryNotFound {
            get {
                return ResourceManager.GetString("MsgEmailTemplateDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template at {filePath} not found.
        /// </summary>
        internal static string MsgEmailTemplateNotFound {
            get {
                return ResourceManager.GetString("MsgEmailTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to address could not be null.
        /// </summary>
        internal static string MsgEmailToCouldNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("MsgEmailToCouldNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email zip directory could not be null.
        /// </summary>
        internal static string MsgEmailZipDirectoryCouldNotBeNull {
            get {
                return ResourceManager.GetString("MsgEmailZipDirectoryCouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email zip path {filePath} could not be found.
        /// </summary>
        internal static string MsgEmailZipDirectoryNotFound {
            get {
                return ResourceManager.GetString("MsgEmailZipDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {filePath} not found.
        /// </summary>
        internal static string MsgFileNotFound {
            get {
                return ResourceManager.GetString("MsgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} must be of type {type}.
        /// </summary>
        internal static string MsgMustBeOfType {
            get {
                return ResourceManager.GetString("MsgMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} could not be null.
        /// </summary>
        internal static string MsgNullOrEmpty {
            get {
                return ResourceManager.GetString("MsgNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {paramName} is required.
        /// </summary>
        internal static string MsgRequiredParameter {
            get {
                return ResourceManager.GetString("MsgRequiredParameter", resourceCulture);
            }
        }
    }
}
