//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oluso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oluso.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid boolean result.
        /// </summary>
        internal static string MsgBooleanComparisonFail {
            get {
                return ResourceManager.GetString("MsgBooleanComparisonFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result could not be false.
        /// </summary>
        internal static string MsgComparisonMustBeFalse {
            get {
                return ResourceManager.GetString("MsgComparisonMustBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result could not be true.
        /// </summary>
        internal static string MsgComparisonMustBeTrue {
            get {
                return ResourceManager.GetString("MsgComparisonMustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} could not be greater than {max}.
        /// </summary>
        internal static string MsgGreater {
            get {
                return ResourceManager.GetString("MsgGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation had fail.
        /// </summary>
        internal static string MsgHadFail {
            get {
                return ResourceManager.GetString("MsgHadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} must be in a range between {min} and {max}.
        /// </summary>
        internal static string MsgInRange {
            get {
                return ResourceManager.GetString("MsgInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} is on invalid format.
        /// </summary>
        internal static string MsgInvalidFormat {
            get {
                return ResourceManager.GetString("MsgInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {item} could not be null or empty.
        /// </summary>
        internal static string MsgItemNullException {
            get {
                return ResourceManager.GetString("MsgItemNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} could not be lower than {min}.
        /// </summary>
        internal static string MsgLower {
            get {
                return ResourceManager.GetString("MsgLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} not found.
        /// </summary>
        internal static string MsgNotFound {
            get {
                return ResourceManager.GetString("MsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} or any of his members could be null.
        /// </summary>
        internal static string MsgNullOrAnyNull {
            get {
                return ResourceManager.GetString("MsgNullOrAnyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {source} could not be null or contain any null item.
        /// </summary>
        internal static string MsgNullOrEmpty {
            get {
                return ResourceManager.GetString("MsgNullOrEmpty", resourceCulture);
            }
        }
    }
}
