#!/usr/bin/env bash
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|wip)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid. Use a valid marker" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,250}$"; then
    echo "Aborting commit. Your commit message is too long. Length up tp 250" >&2
    exit 1
fi
