name: Build And Test (dev)

on:
  push:
    branches: [ dev ]

env:
  DOTNET_VERSION: '6.0.101'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Restore dependencies
      run: dotnet restore Trojes.Core.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore Oluso.sln
    - name: Send message to Telegram
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "Compilation result: ${{ job.status }}"

