name: Build And Test (main)

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.101'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
    - name: Restore dependencies
      run: dotnet restore Oluso.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore Oluso.sln
    - name: Test
      run: dotnet test