name: Publish packages

on:
  workflow_dispatch: # allow running the work from manually from Github UI
  push:
    branches: [release] # run when pushing to release branch
  # pull_request:
  #    branches:
  #      - '*'           # run for all pull requests
  release:
    types:
      - published # run when a new github release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPIRIENCE: 1
  DOTNET_LOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    name: Build on ${{ matrix.os }}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET # .Net SDK in the global.json file
        uses: actions/setup-dotnet@v4

      - run: dotnet pack --configuration Release --output ${{env.NuGetDirectory}}

      - uses: action/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-dayrs: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg
